### ISSUE TITLE
Improve readability/code style

### ISSUE THREAD

**Issue by toastwaffle** [KebleBall/KebleBall#138]
Refer to [Google Python style guide](https://google-styleguide.googlecode.com/svn/trunk/pyguide.html).

* [x] pylint everything
* [ ] refactor logic into class methods/helpers
  * views should just call class methods/helpers
  * views should be effectively declarative
* [ ] rearrange to improve legibility (layout)
  * [x] Remove backslash line continuations
* [x] make quotes consistent
* [x] enforce naming conventions
  * ClassName
  * MODULE_CONSTANT_NAME
  * function_name
  * variable_name
* [x] enforce import restrictions (not enforced by pylint, but part of google spec)
  * [x] only import modules, not classes/functions/constants
  * [x] import only one module per line
  * [x] definitely no from x import \*
  * [x] four blocks of imports
    * `__future__`
    * Standard libraries
    * External libraries (e.g. flask + extensions, requests etc)
    * Same package (i.e. kebleball modules)
  * [x] each block in alphabetical order
* [ ] Reduce length of files
  * [x] split up views.admin

**Comment by toastwaffle** [comment]
Includes #174

**Comment by toastwaffle** [comment]
@katrinpadel @Edisach I've done most of the linting and tidying, I think that all that's left now is:
  * Making sure it all still works
  * Reviewing all the changes
  * Refactoring as necessary

I don't think refactoring is as much of a mission as linting was, and we should just do it as and when necessary; otherwise we're probably going to get stuck into a continuous cycle of refactoring without really getting anywhere. Do you agree?

**Comment by katrinpadel** [comment]
I think refactoring as and when noticed/necessary makes the most sense, otherwise loops seem inevitable. So yes, agreed.
